"""
Generates weights.h C header file from a trained Keras model.

Packs ternary weights {-1, 0, +1} from each QuantDense layer into
uint32_t arrays and FP32 output layer weights/biases into float arrays,
and writes them as a C-compatible header file for use by the NPU user-space application.
"""

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import sys
import numpy as np

DEFAULT_INPUT_DIM = 784
DEFAULT_HIDDEN_DIMS = (256, 128, 64)
DEFAULT_NUM_CLASSES = 10

HEADER_TEMPLATE = """\
/* weights.h — Auto-generated by Ternary Edge-RV QAT pipeline */
/* DO NOT EDIT MANUALLY */

#ifndef WEIGHTS_H
#define WEIGHTS_H

#include <stdint.h>

#ifndef NPU_MODEL_FORMAT_VERSION
#define NPU_MODEL_FORMAT_VERSION 2
#endif
#define NPU_MODEL_HAS_QUANT_PARAMS 1
#ifndef NPU_MODEL_LAYER_COUNT
#define NPU_MODEL_LAYER_COUNT 3
#endif
#ifndef NPU_MODEL_WEIGHTS_OFFSET
#define NPU_MODEL_WEIGHTS_OFFSET 0x00001000u
#endif
#ifndef NPU_MODEL_INPUT_OFFSET
#define NPU_MODEL_INPUT_OFFSET 0x0005C000u
#endif
#ifndef NPU_MODEL_OUTPUT_OFFSET
#define NPU_MODEL_OUTPUT_OFFSET 0x00000000u
#endif
#ifndef NPU_MODEL_BIAS_OFFSET
#define NPU_MODEL_BIAS_OFFSET 0x0005f000u
#endif
#ifndef NPU_MODEL_SCALE_OFFSET
#define NPU_MODEL_SCALE_OFFSET 0x00061000u
#endif

{layer_declarations}

{output_declarations}

#endif /* WEIGHTS_H */
"""

LAYER_DECL_TEMPLATE = """\
/* Layer: {layer_name} — Input: {input_dim}, Output: {output_dim} */
#define {layer_name_upper}_IN  {input_dim}
#define {layer_name_upper}_OUT {output_dim}
#define {layer_name_upper}_PACKED_WORDS {packed_words}
static const uint32_t {layer_name}_weights[{packed_words}] = {{
{weight_data}
}};
#define {layer_name_upper}_BIAS_COUNT {output_dim}
static const int32_t {layer_name}_bias[{output_dim}] = {{
{bias_data}
}};
#define {layer_name_upper}_SCALE_COUNT {output_dim}
static const int32_t {layer_name}_scale[{output_dim}] = {{
{scale_data}
}};
"""

OUTPUT_DECL_TEMPLATE = """\
/* Output Layer: FP32 Dense {output_input_dim}->{output_classes} */
#define OUTPUT_WEIGHTS_COUNT {output_weights_count}
static const float output_weights[OUTPUT_WEIGHTS_COUNT] = {{
{output_weight_data}
}};

#define OUTPUT_BIAS_COUNT {output_bias_count}
static const float output_bias[OUTPUT_BIAS_COUNT] = {{
{output_bias_data}
}};
"""


def format_float_array(data: np.ndarray, items_per_line: int = 8) -> str:
    lines = []
    count = len(data)
    for i in range(0, count, items_per_line):
        chunk = data[i:i + items_per_line]
        chunk_str = ", ".join(f"{float(val):.8f}f" for val in chunk)
        lines.append(f"  {chunk_str},")
    return "\n".join(lines)


def format_int_array(data: np.ndarray, items_per_line: int = 8) -> str:
    lines = []
    values = [int(value) for value in data]
    for i in range(0, len(values), items_per_line):
        lines.append("  " + ", ".join(str(value) for value in values[i:i + items_per_line]) + ",")
    return "\n".join(lines)


def generate_mock_quant_declarations():
    input_dims = (DEFAULT_INPUT_DIM,) + DEFAULT_HIDDEN_DIMS[:-1]
    layers = [
        ("quant_dense" if index == 0 else f"quant_dense_{index}",
         input_dim, output_dim, (input_dim * output_dim) // 16)
        for index, (input_dim, output_dim)
        in enumerate(zip(input_dims, DEFAULT_HIDDEN_DIMS))
    ]
    declarations = []
    for layer_name, in_dim, out_dim, packed_words in layers:
        upper = layer_name.upper().replace("-", "_")
        weight_lines = ["  0x00000000,"] * packed_words
        weight_data = "\n".join(weight_lines)
        decl = LAYER_DECL_TEMPLATE.format(
            layer_name=layer_name,
            layer_name_upper=upper,
            input_dim=in_dim,
            output_dim=out_dim,
            packed_words=packed_words,
            weight_data=weight_data,
            bias_data=format_int_array(np.zeros(out_dim, dtype=np.int32)),
            scale_data=format_int_array(np.ones(out_dim, dtype=np.int32)),
        )
        declarations.append(decl)
    return declarations


def generate_weights_header(model_path: str, output_path: str):
    quant_declarations = []
    output_weights_vals = None
    output_bias_vals = None
    output_input_dim = DEFAULT_HIDDEN_DIMS[-1]
    output_classes = DEFAULT_NUM_CLASSES

    if os.path.exists(model_path):
        import tensorflow as tf
        if not hasattr(tf.keras.layers, "LocallyConnected1D"):
            tf.keras.layers.LocallyConnected1D = type("LocallyConnected1D", (), {})
        import larq as lq
        from pack_weights import pack_weights

        print(f"Loading model from {model_path}...")
        model = tf.keras.models.load_model(model_path, compile=False)

        quant_layers = [
            l for l in model.layers
            if isinstance(l, lq.layers.QuantDense)
        ]

        expected_quant_dims = list(zip(
            (DEFAULT_INPUT_DIM,) + DEFAULT_HIDDEN_DIMS[:-1],
            DEFAULT_HIDDEN_DIMS,
        ))
        actual_quant_dims = [
            tuple(layer.get_weights()[0].shape) for layer in quant_layers
        ]
        if actual_quant_dims != expected_quant_dims:
            raise ValueError(
                f"Model QuantDense dimensions {actual_quant_dims} do not match "
                f"the export contract {expected_quant_dims}. Retrain the model."
            )

        for layer in quant_layers:
            w_float = layer.get_weights()[0]
            w_quant = layer.kernel_quantizer(tf.constant(w_float)).numpy()
            input_dim, output_dim = w_float.shape
            packed = pack_weights(w_quant)
            packed_words = len(packed)
            raw_weights = layer.get_weights()
            biases = raw_weights[1] if len(raw_weights) > 1 else np.zeros(output_dim, dtype=np.int32)
            biases = np.rint(biases).astype(np.int32)
            scales = np.ones(output_dim, dtype=np.int32)

            weight_lines = []
            for word in packed:
                weight_lines.append(f"  0x{word:08X},")
            weight_data = "\n".join(weight_lines)

            upper = layer.name.upper().replace("-", "_")
            decl = LAYER_DECL_TEMPLATE.format(
                layer_name=layer.name,
                layer_name_upper=upper,
                input_dim=input_dim,
                output_dim=output_dim,
                packed_words=packed_words,
                weight_data=weight_data,
                bias_data=format_int_array(biases),
                scale_data=format_int_array(scales),
            )
            quant_declarations.append(decl)

        # Inspect model for final Dense layer (output layer)
        output_layer = None
        for layer in reversed(model.layers):
            if isinstance(layer, tf.keras.layers.Dense) and not isinstance(layer, lq.layers.QuantDense):
                output_layer = layer
                break

        if output_layer is not None and len(output_layer.get_weights()) > 0:
            weights = output_layer.get_weights()
            w_float = weights[0]
            b_float = weights[1] if len(weights) > 1 else np.zeros(10, dtype=np.float32)
            output_input_dim, output_classes = w_float.shape
            expected_output_dims = (DEFAULT_HIDDEN_DIMS[-1], DEFAULT_NUM_CLASSES)
            if (output_input_dim, output_classes) != expected_output_dims:
                raise ValueError(
                    f"Output Dense dimensions {(output_input_dim, output_classes)} "
                    f"do not match the export contract {expected_output_dims}."
                )
            # Store one contiguous row per output class for the C classifier.
            output_weights_vals = w_float.T.flatten()
            output_bias_vals = b_float.flatten()
        else:
            print("Output Dense layer not found in model, using fallback non-zero weights.")

    else:
        print(f"Model file not found at {model_path}.")
        print("Generating mock QuantDense declarations.")
        quant_declarations = generate_mock_quant_declarations()

    if output_weights_vals is None:
        output_weights_vals = np.full(
            DEFAULT_HIDDEN_DIMS[-1] * DEFAULT_NUM_CLASSES, 0.01, dtype=np.float32
        )
        output_bias_vals = np.full(DEFAULT_NUM_CLASSES, 0.1, dtype=np.float32)

    output_weight_data = format_float_array(output_weights_vals)
    output_bias_data = format_float_array(output_bias_vals)

    output_decl = OUTPUT_DECL_TEMPLATE.format(
        output_input_dim=output_input_dim,
        output_classes=output_classes,
        output_weights_count=len(output_weights_vals),
        output_weight_data=output_weight_data,
        output_bias_count=len(output_bias_vals),
        output_bias_data=output_bias_data,
    )

    header = HEADER_TEMPLATE.format(
        layer_declarations="\n\n".join(quant_declarations),
        output_declarations=output_decl,
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"Generated {output_path} successfully.")


if __name__ == "__main__":
    default_model = os.path.join(os.path.dirname(__file__), "ternary_mnist_qat.h5")
    default_output = os.path.join(os.path.dirname(__file__), "..", "..", "software", "user_app", "weights.h")

    model_path = sys.argv[1] if len(sys.argv) > 1 else default_model
    output_path = sys.argv[2] if len(sys.argv) > 2 else default_output

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    generate_weights_header(model_path, output_path)
