"""
Generates weights.h C header file from a trained Keras model.

Packs ternary weights {-1, 0, +1} from each QuantDense layer into
uint32_t arrays and FP32 output layer weights/biases into float arrays,
and writes them as a C-compatible header file for use by the NPU user-space application.
"""

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import sys
import numpy as np

HEADER_TEMPLATE = """\
/* weights.h — Auto-generated by Ternary Edge-RV QAT pipeline */
/* DO NOT EDIT MANUALLY */

#ifndef WEIGHTS_H
#define WEIGHTS_H

#include <stdint.h>

{layer_declarations}

{output_declarations}

#endif /* WEIGHTS_H */
"""

LAYER_DECL_TEMPLATE = """\
/* Layer: {layer_name} — Input: {input_dim}, Output: {output_dim} */
#define {layer_name_upper}_IN  {input_dim}
#define {layer_name_upper}_OUT {output_dim}
#define {layer_name_upper}_PACKED_WORDS {packed_words}
static const uint32_t {layer_name}_weights[{packed_words}] = {{
{weight_data}
}};
"""

OUTPUT_DECL_TEMPLATE = """\
/* Output Layer: FP32 Dense 256->10 */
#define OUTPUT_WEIGHTS_COUNT {output_weights_count}
static const float output_weights[OUTPUT_WEIGHTS_COUNT] = {{
{output_weight_data}
}};

#define OUTPUT_BIAS_COUNT {output_bias_count}
static const float output_bias[OUTPUT_BIAS_COUNT] = {{
{output_bias_data}
}};
"""


def format_float_array(data: np.ndarray, items_per_line: int = 8) -> str:
    lines = []
    count = len(data)
    for i in range(0, count, items_per_line):
        chunk = data[i:i + items_per_line]
        chunk_str = ", ".join(f"{float(val):.8f}f" for val in chunk)
        lines.append(f"  {chunk_str},")
    return "\n".join(lines)


def generate_mock_quant_declarations():
    layers = [
        ("quant_dense", 784, 1024, 50176),
        ("quant_dense_1", 1024, 512, 32768),
        ("quant_dense_2", 512, 256, 8192),
    ]
    declarations = []
    for layer_name, in_dim, out_dim, packed_words in layers:
        upper = layer_name.upper().replace("-", "_")
        weight_lines = [f"  0x10000010,"] * packed_words
        weight_data = "\n".join(weight_lines)
        decl = LAYER_DECL_TEMPLATE.format(
            layer_name=layer_name,
            layer_name_upper=upper,
            input_dim=in_dim,
            output_dim=out_dim,
            packed_words=packed_words,
            weight_data=weight_data,
        )
        declarations.append(decl)
    return declarations


def generate_weights_header(model_path: str, output_path: str):
    quant_declarations = []
    output_weights_vals = None
    output_bias_vals = None

    if os.path.exists(model_path):
        import tensorflow as tf
        if not hasattr(tf.keras.layers, "LocallyConnected1D"):
            tf.keras.layers.LocallyConnected1D = type("LocallyConnected1D", (), {})
        import larq as lq
        from pack_weights import pack_weights

        print(f"Loading model from {model_path}...")
        model = tf.keras.models.load_model(model_path, compile=False)

        quant_layers = [
            l for l in model.layers
            if isinstance(l, lq.layers.QuantDense)
        ]

        for layer in quant_layers:
            w_float = layer.get_weights()[0]
            w_quant = layer.kernel_quantizer(tf.constant(w_float)).numpy()
            input_dim, output_dim = w_float.shape
            packed = pack_weights(w_quant)
            packed_words = len(packed)

            weight_lines = []
            for word in packed:
                weight_lines.append(f"  0x{word:08X},")
            weight_data = "\n".join(weight_lines)

            upper = layer.name.upper().replace("-", "_")
            decl = LAYER_DECL_TEMPLATE.format(
                layer_name=layer.name,
                layer_name_upper=upper,
                input_dim=input_dim,
                output_dim=output_dim,
                packed_words=packed_words,
                weight_data=weight_data,
            )
            quant_declarations.append(decl)

        # Inspect model for final Dense layer (output layer)
        output_layer = None
        for layer in reversed(model.layers):
            if isinstance(layer, tf.keras.layers.Dense) and not isinstance(layer, lq.layers.QuantDense):
                output_layer = layer
                break

        if output_layer is not None and len(output_layer.get_weights()) > 0:
            weights = output_layer.get_weights()
            w_float = weights[0]  # shape (256, 10)
            b_float = weights[1] if len(weights) > 1 else np.zeros(10, dtype=np.float32)
            # Transpose to (10, 256) so indexing in C as weights[10][256] matches
            output_weights_vals = w_float.T.flatten()
            output_bias_vals = b_float.flatten()
        else:
            print("Output Dense layer not found in model, using fallback non-zero weights.")

    else:
        print(f"Model file not found at {model_path}.")
        if os.path.exists(output_path):
            with open(output_path, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
            if "quant_dense_weights" in content and "quant_dense_1_weights" in content and "quant_dense_2_weights" in content:
                print(f"Preserving existing QuantDense declarations from {output_path}.")
                cutoff_markers = ["/* Output", "OUTPUT_WEIGHTS", "output_weights", "OUTPUT_BIAS", "output_bias", "#endif"]
                cutoff_indices = [content.find(m) for m in cutoff_markers if content.find(m) != -1]
                cutoff = min(cutoff_indices) if cutoff_indices else len(content)
                quant_part = content[:cutoff].strip()
                start_idx = quant_part.find("/* Layer:")
                if start_idx != -1:
                    quant_declarations = [quant_part[start_idx:].strip()]

        if not quant_declarations:
            print("Generating mock QuantDense declarations.")
            quant_declarations = generate_mock_quant_declarations()

    if output_weights_vals is None:
        output_weights_vals = np.full(2560, 0.01, dtype=np.float32)
        output_bias_vals = np.full(10, 0.1, dtype=np.float32)

    output_weight_data = format_float_array(output_weights_vals)
    output_bias_data = format_float_array(output_bias_vals)

    output_decl = OUTPUT_DECL_TEMPLATE.format(
        output_weights_count=len(output_weights_vals),
        output_weight_data=output_weight_data,
        output_bias_count=len(output_bias_vals),
        output_bias_data=output_bias_data,
    )

    header = HEADER_TEMPLATE.format(
        layer_declarations="\n\n".join(quant_declarations),
        output_declarations=output_decl,
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"Generated {output_path} successfully.")


if __name__ == "__main__":
    default_model = os.path.join(os.path.dirname(__file__), "ternary_mnist_qat.h5")
    default_output = os.path.join(os.path.dirname(__file__), "..", "..", "software", "user_app", "weights.h")

    model_path = sys.argv[1] if len(sys.argv) > 1 else default_model
    output_path = sys.argv[2] if len(sys.argv) > 2 else default_output

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    generate_weights_header(model_path, output_path)

