"""
Generates weights.h C header file from a trained Keras model.

Packs ternary weights {-1, 0, +1} from each QuantDense layer into
uint32_t arrays and writes them as a C-compatible header file
for use by the NPU user-space application.
"""

import os
import sys
import numpy as np
import tensorflow as tf
import larq as lq
from pack_weights import pack_weights

os.environ["TF_USE_LEGACY_KERAS"] = "1"

HEADER_TEMPLATE = """\
/* weights.h — Auto-generated by Ternary Edge-RV QAT pipeline */
/* DO NOT EDIT MANUALLY */

#ifndef WEIGHTS_H
#define WEIGHTS_H

#include <stdint.h>

{layer_declarations}

#endif /* WEIGHTS_H */
"""

LAYER_DECL_TEMPLATE = """\
/* Layer: {layer_name} — Input: {input_dim}, Output: {output_dim} */
#define {layer_name_upper}_IN  {input_dim}
#define {layer_name_upper}_OUT {output_dim}
#define {layer_name_upper}_PACKED_WORDS {packed_words}
static const uint32_t {layer_name}_weights[{packed_words}] = {{
{weight_data}
}};
"""


def generate_weights_header(model_path: str, output_path: str):
    model = tf.keras.models.load_model(model_path, compile=False)

    quant_layers = [
        l for l in model.layers
        if isinstance(l, lq.layers.QuantDense)
    ]

    declarations = []
    for layer in quant_layers:
        w = layer.get_weights()[0]
        input_dim, output_dim = w.shape
        packed = pack_weights(w)
        packed_words = len(packed)

        weight_lines = []
        for i, word in enumerate(packed):
            if (i + 1) % 8 == 0 or i == len(packed) - 1:
                weight_lines.append(f"    0x{word:08X},")
            else:
                weight_lines.append(f"0x{word:08X}, ")

        weight_data = "\n".join(weight_lines)

        upper = layer.name.upper().replace("-", "_")
        decl = LAYER_DECL_TEMPLATE.format(
            layer_name=layer.name,
            layer_name_upper=upper,
            input_dim=input_dim,
            output_dim=output_dim,
            packed_words=packed_words,
            weight_data=weight_data,
        )
        declarations.append(decl)

    header = HEADER_TEMPLATE.format(
        layer_declarations="\n\n".join(declarations)
    )

    with open(output_path, "w") as f:
        f.write(header)

    print(f"Generated {output_path} with {len(quant_layers)} layers")
    total_words = sum(
        len(pack_weights(l.get_weights()[0]))
        for l in quant_layers
    )
    print(f"Total packed words: {total_words}")
    print(f"Total bytes: {total_words * 4}")


if __name__ == "__main__":
    default_model = os.path.join(os.path.dirname(__file__), "ternary_mnist_qat.h5")
    default_output = os.path.join(os.path.dirname(__file__), "..", "..", "software", "user_app", "weights.h")

    model_path = sys.argv[1] if len(sys.argv) > 1 else default_model
    output_path = sys.argv[2] if len(sys.argv) > 2 else default_output

    if not os.path.exists(model_path):
        print(f"Error: Model file not found at {model_path}")
        sys.exit(1)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    generate_weights_header(model_path, output_path)
