NPU_TERNARIA_VERSION = 1.0
NPU_TERNARIA_SITE = $(BR2_EXTERNAL_TERNARYEDGE_RV_PATH)/../npu_driver
NPU_TERNARIA_SITE_METHOD = local

define NPU_TERNARIA_COPY_IOCTL_H
    cp $(BR2_EXTERNAL_TERNARYEDGE_RV_PATH)/../include/npu_ioctl.h $(@D)/npu_ioctl.h
endef
NPU_TERNARIA_POST_RSYNC_HOOKS += NPU_TERNARIA_COPY_IOCTL_H

$(eval $(kernel-module))
