/*
 * user_app.c — NPU v2 User-Space Inference & Benchmark Application
 * Ternary Edge-RV Project
 *
 * This application:
 *   1. Opens /dev/npu_ternaria
 *   2. Maps the DMA buffer (zero-copy)
 *   3. Loads packed ternary weights and INT8 activations into the DMA buffer
 *   4. Calls IOCTL to start hardware inference (CPU sleeps during NPU compute)
 *   5. Measures segregated timing (DMA setup, inference, readback)
 *   6. Reads and displays results
 *
 * Compile for RISC-V:
 *   riscv32-buildroot-linux-gnu-gcc -static -o user_app user_app.c
 *
 * Author: Gilvan Alves Pastor Junior + Gustavo Alexandre dos Santos
 * Version: 2.0 (NPU v2)
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/ioctl.h>
#include <sys/time.h>
#include <string.h>
#include <errno.h>

#include "../include/npu_ioctl.h"

/* =========================================================================
 * Device path
 * ========================================================================= */
#define DEVICE_PATH "/dev/npu_ternaria"

/* =========================================================================
 * Forward-pass function (software baseline for comparison)
 *
 * Computes a dense ternary layer: output[j] = Σ(input[i] × weight[i][j])
 * for all j. Weights are packed 16 per uint32_t.
 * Encoding: +1 = 0b01, 0 = 0b00, -1 = 0b11 (Little-Endian)
 * ========================================================================= */
static void forward_ternary_layer(int32_t *output,
                                   const uint8_t *input,
                                   const uint32_t *packed_weights,
                                   const int32_t *bias,
                                   int num_inputs, int num_outputs)
{
    for (int j = 0; j < num_outputs; j++) {
        int32_t acc = 0;

        for (int i = 0; i < num_inputs; i++) {
            int word_idx = j * (num_inputs / 16) + i / 16;
            int bit_pos = (i % 16) * 2;
            uint8_t weight = (packed_weights[word_idx] >> bit_pos) & 0x03;

            int8_t act = (int8_t)input[i];
            if (weight == 0b01) {
                acc += act;           // weight = +1
            } else if (weight == 0b11) {
                acc -= act;           // weight = -1
            }
            /* weight = 0b00: skip (sparsity) */
        }

        output[j] = acc + bias[j];
    }
}

/* =========================================================================
 * Timing helper
 * ========================================================================= */
static long time_diff_us(struct timeval *start, struct timeval *end)
{
    return (end->tv_sec - start->tv_sec) * 1000000L +
           (end->tv_usec - start->tv_usec);
}

/* =========================================================================
 * Main
 * ========================================================================= */
int main(int argc, char **argv)
{
    int fd;
    uint32_t *dma_buffer;
    struct npu_ioctl_args ioctl_args;
    struct timeval t0, t1, t2, t3;
    long t_setup_us, t_inference_us, t_readback_us;

    printf("============================================\n");
    printf(" Ternary Edge-RV — NPU v2 Inference Benchmark\n");
    printf(" 64 MACs | Wishbone Master DMA | IRQ Sync\n");
    printf("============================================\n");

    /* ---- 1. Open device ---- */
    fd = open(DEVICE_PATH, O_RDWR);
    if (fd < 0) {
        perror("Failed to open " DEVICE_PATH);
        return EXIT_FAILURE;
    }
    printf("[OK] Device opened: %s\n", DEVICE_PATH);

    /* ---- 2. Map DMA buffer (zero-copy) ---- */
    dma_buffer = mmap(NULL, NPU_DMA_BUFFER_SIZE,
                      PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (dma_buffer == MAP_FAILED) {
        perror("Failed to mmap DMA buffer");
        close(fd);
        return EXIT_FAILURE;
    }
    printf("[OK] DMA buffer mapped: %p (%u MB)\n",
           (void*)dma_buffer, NPU_DMA_BUFFER_SIZE / (1024 * 1024));

    /* ---- 3. Load weights and activations into DMA buffer ---- */
    gettimeofday(&t0, NULL);

    /*
     * DMA buffer layout:
     *   [0..ACT_BYTES-1]:         INT8 activations (packed 4/word)
     *   [ACT_BYTES..ACT_BYTES+WEIGHT_BYTES-1]: Packed ternary weights
     *   [last 1KB]:               Result buffer
     *
     * The weights.h file is generated by ai_training/scripts/generate_weights_h.py
     * For this benchmark, we use synthetic test data.
     */
    {
        const int act_bytes = 784;  /* MNIST image size */
        const int num_weights = 50176 + 32768 + 8192;  /* Total weight words */

        /* Fill activations with test pattern */
        for (int i = 0; i < act_bytes; i++) {
            ((uint8_t*)dma_buffer)[i] = (uint8_t)((i * 13 + 7) % 128);
        }

        /* Weights are already packed — in production, include weights.h */
        /* Here we fill with a mix of +1 and 0 for testing */
        for (int i = 0; i < num_weights; i++) {
            uint32_t word = 0;
            for (int b = 0; b < 16; b++) {
                /* ~80% zeros, 10% +1, 10% -1 (simulating L1 sparsity) */
                int r = (i * 31 + b * 7) % 100;
                if (r < 10)
                    word |= ((uint32_t)0b01) << (b * 2);   /* +1 */
                else if (r < 20)
                    word |= ((uint32_t)0b11) << (b * 2);   /* -1 */
                /* else: 0b00 = zero (sparsity) */
            }
            ((uint32_t*)((uint8_t*)dma_buffer + 4096))[i] = word;
        }
    }
    gettimeofday(&t1, NULL);
    t_setup_us = time_diff_us(&t0, &t1);
    printf("[OK] Data loaded into DMA buffer (%ld us)\n", t_setup_us);

    /* ---- 4. Configure and start hardware inference ---- */
    ioctl_args.dma_size    = 50176 + 32768 + 8192;  /* Total weight words */
    ioctl_args.weight_cfg  = 50176;                   /* Words in layer 0 */
    ioctl_args.act_cfg     = 784;                     /* Activations */
    ioctl_args.mac_cfg     = 64;                      /* 64 MACs */
    ioctl_args.layer_cfg   = 3;                       /* 3 layers */

    printf("[...] Starting NPU inference (CPU will sleep)...\n");

    gettimeofday(&t1, NULL);

    if (ioctl(fd, NPU_IOCTL_START_INFERENCE, &ioctl_args) < 0) {
        fprintf(stderr, "IOCTL failed: %s\n", strerror(errno));
        munmap(dma_buffer, NPU_DMA_BUFFER_SIZE);
        close(fd);
        return EXIT_FAILURE;
    }

    gettimeofday(&t2, NULL);
    t_inference_us = time_diff_us(&t1, &t2);

    /* ---- 5. Read results ---- */
    uint32_t result = dma_buffer[0];  /* First word of result buffer */
    gettimeofday(&t3, NULL);
    t_readback_us = time_diff_us(&t2, &t3);

    printf("[OK] Inference complete! IRQ received.\n");
    printf("     Result: 0x%08X (%d)\n", result, (int32_t)result);

    /* ---- 6. Print benchmark ---- */
    printf("\n========== BENCHMARK ==========\n");
    printf("  DMA setup:     %ld us\n", t_setup_us);
    printf("  NPU inference: %ld us  (CPU was ASLEEP)\n", t_inference_us);
    printf("  Readback:      %ld us\n", t_readback_us);
    printf("  Total:         %ld us\n",
           t_setup_us + t_inference_us + t_readback_us);
    printf("================================\n");

    /* ---- 7. Software baseline comparison (optional) ---- */
    printf("\n[INFO] To compare: run with --cpu flag\n");
    if (argc > 1 && strcmp(argv[1], "--cpu") == 0) {
        const int num_inputs[]  = { 784, 1024, 512 };
        const int num_outputs[] = { 1024, 512, 256 };
        int32_t layer_out[1024];

        gettimeofday(&t0, NULL);

        /* Layer 0 */
        forward_ternary_layer(layer_out,
                              (uint8_t*)dma_buffer,
                              (uint32_t*)((uint8_t*)dma_buffer + 4096),
                              NULL, 784, 1024);

        /* Layer 1 */
        forward_ternary_layer((int32_t*)((uint8_t*)dma_buffer + 8192),
                              (uint8_t*)layer_out,
                              (uint32_t*)((uint8_t*)dma_buffer + 4096 + 50176*4),
                              NULL, 1024, 512);

        /* Layer 2 */
        int32_t final_out[256];
        forward_ternary_layer(final_out,
                              (uint8_t*)((int32_t*)((uint8_t*)dma_buffer + 8192)),
                              (uint32_t*)((uint8_t*)dma_buffer + 4096 + (50176+32768)*4),
                              NULL, 512, 256);

        gettimeofday(&t1, NULL);
        long cpu_us = time_diff_us(&t0, &t1);
        printf("\n  CPU software baseline: %ld us\n", cpu_us);
        printf("  Speedup (NPU vs CPU): %.1fx\n",
               (double)cpu_us / (double)(t_inference_us ? t_inference_us : 1));
    }

    /* ---- Cleanup ---- */
    munmap(dma_buffer, NPU_DMA_BUFFER_SIZE);
    close(fd);

    printf("\nDone.\n");
    return EXIT_SUCCESS;
}
